review/musicians/urls.py
from django.urls import path
from . import views

#어플리케이션 name space
app_name = "musicians"

#장고 내부적으로 정해진 이름.
urlpatterns = [
    # u - v - t 순서 고정.
    #path_name을 무엇으로 지었는지,
    #어떤 view 함수를 실행하였는지
    #하나의 경로에는 하나의 view 함수
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    # django가 지정한 경로 작성 방식
    # <데이터 타입 : 변수 명>
    # 실제 사용자가 작성하는 url
    # '3/'
    path('<int:musician_pk>/detail/', views.detail, name="detail"),
    path('<int:musician_pk>/update/', views.update, name="update"),
    path('<int:musician_pk>/delete/', views.delete, name="delete"),
]

review/review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('musicians/', include('musicians.urls')),
]

review/musicians/models.py
from django.db import models

# Create your models here.
# 객체 생성(클래스 생성) -> 테이블 명
class Musician(models.Model):
    # 멤버 변수
    # name = '이름이란 사람이 가지는 공통 특성'
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    #인스턴스 호출 시 출력 내용 덮어쓰기
    def __str__(self):
        return f'{self.id}번 - {self.name} : {self.age}'

review/musicians/forms.py
# 장고에서 미리 정의해둔 forms 받아오기
from django import forms
# models에서 정의한 Musicians 객체 받아오기
from .models import Musician

# 클래스 정의
class MusicianForm(forms.ModelForm):
    # 클래스에 대한 클래스
    class Meta:
        # 어떤 모델? Musician에 정의된 것
        model = Musician
        # fields = ['name','app']
        fields = '__all__'

review/musicians/views.py
from django.shortcuts import render,redirect
from .forms import MusicianForm
from .models import Musician

# Create your views here.
# 함수정의 함수이름(parameter):
def index(request):
    musicians = Musician.objects.all()
    context = {
        'musicians':musicians
    }
    return render(request, 'musicians/index.html', context)

def create(request):
    if request.method == "POST":
        # 사용자의 요청 정보를 담아준다.
        form = MusicianForm(request.POST)
        # forms를 상속받았기 때문에 사용가능
        if form.is_valid():
            # Musician이 models에게 받은 메서드
            # ModelForm 을 정의 할 때
            # class Meta : 
            # model- Musician을 담아줬다
            musician = form.save()
            # redirect('app_name : path_name')
            return redirect('musicians:index')
    else:
        # MusicianForm 불러오기
        # form은 MusicianForm 인스턴스
        # MusicianForm이 가진 정보를 가짐.
        # MusicianForm은 Musician의 정보
        # template에서 보여줄 tag들
        form = MusicianForm()
    context ={
        'form':form
    }
    return render(request, 'musicians/create.html', context)

# 함수정의 함수이름(request, url에 작성한 변수명)
def detail(request, musician_pk):
    # Model.objects.get(조건=변수명)
    musician = Musician.objects.get(pk=musician_pk)
    context = {
        'musician': musician
    }
    return render(request,'musicians/detail.html', context)

def update(request,musician_pk):
    musician = Musician.objects.get(pk=musician_pk)
    if request.method == "POST":
        form = MusicianForm(request.POST, instance=musician)
        if form.is_valid():
            musician = form.save()
            return redirect('musicians:index')
    else:
        form = MusicianForm(instance = musician)
        context = {
            'form':form
        }
    return render(request, 'musicians/create.html',context)

def delete(request, musician_pk):
    musician = Musician.objects.get(pk=musician_pk)
    musician.delete()
    return redirect('musicians:index')

review/musicians/templates/musicians/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
  {% else %}
  <h1>글 수정</h1>
  {% endif %}
  <!-- action을 비워두면 현재 위치로 요청 -->
  <!-- 차이점 : method를 지정해줬다. -->
  <!-- a tag : GET -->
  <form action="" method="POST">
    {% csrf_token %}
    <!-- views에서 context에 담아 넘겨준 form -->
    {{ form }}
    <button type="submit">
      submit
    </button>
  </form>
</body>
</html>

review/musicians/templates/musicians/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>상세 페이지</h1>
  <hr>
  <!-- Musician 은 결국 인스턴스다 -->
  <h1>{{ musician }}</h1>
  <hr>
  <!-- 각 변수에 접근할 수 있다 -->
  <p>{{ musician.name }}</p>
  <p>{{ musician.age }}</p>
  <a href="{% url 'musicians:update' musician.pk %}">글 수정</a>
  <a href="{% url 'musicians:delete' musician.pk %}">글 삭제</a>
</body>
</html>

review/musicians/templates/musicians/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index</title>
</head>
<body>
  <h1>메인 페이지</h1>
  <br>
  <ul>
    {% for musician in musicians %}
      <a href="{% url 'musicians:detail' musician.pk %}">
          <li>{{musician}}</li>
      </a>
    {% endfor %}

  </ul>
  <a href="{% url 'musicians:create' %}">글 생성</a>
</body>
</html>